apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    network-policy-generator.stackrox.io/generated: "true"
  name: stackrox-generated-welcome
  namespace: v3-app
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          namespace.metadata.stackrox.io/name: v3-web
      podSelector:
        matchLabels:
          service: apigateway-v2
    ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      app: welcome
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    network-policy-generator.stackrox.io/generated: "true"
  name: stackrox-generated-mobile-facility-service-v1
  namespace: v3-app
spec:
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      service: mobile-facility-service-v1
  policyTypes:
  - Ingress
