apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-04-14T18:08:42Z"
  labels:
    network-policy-generator.stackrox.io/generated: "true"
  name: stackrox-generated-welcome
  namespace: v3-app
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          namespace.metadata.stackrox.io/name: v3-web
      podSelector:
        matchLabels:
          service: apigateway-v2
    ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      app: welcome
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-04-14T18:08:42Z"
  labels:
    network-policy-generator.stackrox.io/generated: "true"
  name: stackrox-generated-mobile-facility-service-v1
  namespace: v3-app
spec:
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      service: mobile-facility-service-v1
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-04-14T18:08:42Z"
  labels:
    network-policy-generator.stackrox.io/generated: "true"
  name: stackrox-generated-mhs-video-connect
  namespace: v3-app
spec:
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      service: mhs-video-connect
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-04-14T18:08:42Z"
  labels:
    network-policy-generator.stackrox.io/generated: "true"
  name: stackrox-generated-mobile-vmr-service-v1
  namespace: v3-app
spec:
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      service: mobile-vmr-service-v1
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-04-14T18:08:42Z"
  labels:
    network-policy-generator.stackrox.io/generated: "true"
  name: stackrox-generated-apt-reminder-publisher
  namespace: v3-app
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          service: video-visits-service-v1
    ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      service: apt-reminder-publisher
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-04-14T18:08:42Z"
  labels:
    network-policy-generator.stackrox.io/generated: "true"
  name: stackrox-generated-blackhole-service-v1
  namespace: v3-app
spec:
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      service: blackhole-service-v1
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-04-14T18:08:42Z"
  labels:
    network-policy-generator.stackrox.io/generated: "true"
  name: stackrox-generated-user-services-v2
  namespace: v3-app
spec:
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      service: user-services-v2
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-04-14T18:08:42Z"
  labels:
    network-policy-generator.stackrox.io/generated: "true"
  name: stackrox-generated-apigateway-v2
  namespace: v3-web
spec:
  ingress:
  - ports:
    - port: 8443
      protocol: TCP
  - ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      service: apigateway-v2
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-04-14T18:08:42Z"
  labels:
    network-policy-generator.stackrox.io/generated: "true"
  name: stackrox-generated-video-visits-service-v1
  namespace: v3-app
spec:
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      service: video-visits-service-v1
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-04-14T18:08:42Z"
  labels:
    network-policy-generator.stackrox.io/generated: "true"
  name: stackrox-generated-personal-preferences-service
  namespace: v3-app
spec:
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      service: personal-preferences-service
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-04-14T18:08:42Z"
  labels:
    network-policy-generator.stackrox.io/generated: "true"
  name: stackrox-generated-authorization-rules-service-v1
  namespace: v3-app
spec:
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      service: authorization-rules-service-v1
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-04-14T18:08:42Z"
  labels:
    network-policy-generator.stackrox.io/generated: "true"
  name: stackrox-generated-video-session-info-service-v1
  namespace: v3-app
spec:
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      service: video-session-info-service-v1
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-04-14T18:08:42Z"
  labels:
    network-policy-generator.stackrox.io/generated: "true"
  name: stackrox-generated-apt-reminder-subscriber
  namespace: v3-app
spec:
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      service: apt-reminder-subscriber
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-04-14T18:08:42Z"
  labels:
    network-policy-generator.stackrox.io/generated: "true"
  name: stackrox-generated-telehealth-rabbitmq
  namespace: v3-app
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: telehealth-rabbitmq
    ports:
    - port: 4369
      protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          app: telehealth-rabbitmq
    ports:
    - port: 25672
      protocol: TCP
  - ports:
    - port: 5672
      protocol: TCP
  podSelector:
    matchLabels:
      app: telehealth-rabbitmq
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-04-14T18:08:42Z"
  labels:
    network-policy-generator.stackrox.io/generated: "true"
  name: stackrox-generated-logger-service-v1
  namespace: v3-app
spec:
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      service: logger-service-v1
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-04-14T18:08:42Z"
  labels:
    network-policy-generator.stackrox.io/generated: "true"
  name: stackrox-generated-config-service-v1
  namespace: v3-app
spec:
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      service: config-service-v1
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-04-14T18:08:42Z"
  labels:
    network-policy-generator.stackrox.io/generated: "true"
  name: stackrox-generated-provider-preferences-service-v1
  namespace: v3-app
spec:
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      service: provider-preferences-service-v1
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-04-14T18:08:42Z"
  labels:
    network-policy-generator.stackrox.io/generated: "true"
  name: stackrox-generated-virtual-care-manager
  namespace: v3-app
spec:
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      service: virtual-care-manager
  policyTypes:
  - Ingress

